use_default_settings: true

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "tsu_research_project_mcp_orchestrator_2026"
  limiter: false
  image_proxy: true
  base_url: "http://127.0.0.1:8080/"

redis:
  url: redis://redis:6379/0

search:
  safe_search: 0
  formats:
    - html
    - json
  default_lang: "ru"

engines:
  - name: google
    engine: google
    categories: general
  - name: duckduckgo
    engine: duckduckgo
    categories: general
  - name: stackoverflow
    engine: stackoverflow
    categories: it
  - name: github
    engine: github
    categories: it
  - name: arxiv
    engine: arxiv
    categories: science