version: '3.8'

services:
  redis:
    container_name: searxng-redis
    image: redis:alpine
    command: redis-server --save "" --appendonly "no"
    restart: unless-stopped

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:ro
    environment:
      - SEARXNG_SETTINGS_PATH=/etc/searxng/settings.yml
      - TZ=Europe/Moscow
    depends_on:
      - redis